### PR TITLE
add Http4sTestHttpRoutesSuite & Http4sTestAuthedRoutesSuite

### PR DESCRIPTION
**Pull request by JackTreble**
Adding this allows for more granular route tests

Real world example can be found in Http4sTestHttpRoutesSuiteSuite - https://github.com/alejandrohdezma/http4s-munit/pull/246/commits/a495063edf261bb582a4ab99f7d347979f73e859

### CODE REVIEW

**Comment by JackTreble** [comment]
Hey @alejandrohdezma
Thanks for reviewing the changes :smile:  
My original motivation for this change was testing a health check endpoint, I don't think it fits into the existing model as you always make the same request but expect different responses. I expect there are other cases like this.

I'm personally not a fan of this style of testing (conditional logic in the single instance of routes).
It could become unreadable and complicated when you extend past a trivial example. e.g. posting large bodys.
It can leave you open to tests conflicting on change and passing with poorly written code.
your test logic is spread across the file making it less clear what the test is doing.

This can be alleviated with well structured routes & business logic, but we don't always have that luxury :laughing:  

It would be great if we could have both styles of route testing available, It would be easier to adopt it's the style I and others have been using making this library more of a drop in replacement rather than rewrite your tests to fit its paradigm

**Review by alejandrohdezma — APPROVED** [review]

**Comment by alejandrohdezma** [comment]
That makes perfect sense :)

Thanks again!

**Comment by JackTreble** [comment]
@alejandrohdezma 
Thanks for merging :D 
I tried to make the changes non breaking
is there anything i can change ot make it non breaking before the next release?

**Comment by alejandrohdezma** [comment]
I don't see a way, but, TBH it would only affect those extending the `Http4sSuite` directly, which I don't think will be a lot of people (if any) so I don't believe there will be any problem

**Pull request merged**
